version: '3.8'
services:
  api-student-35:
    build: .
    ports:
      - "3035:3000"
    environment:
      DB_URL: mongodb://mongo-student-35:27017/CRMdb-student-35
      PORT: 3000
    depends_on:
      - mongo-student-35
  mongo-student-35:
    image: mongo:latest
    ports:
      - "27052:27017"
    volumes:
      - db-data-student-35:/data/db
volumes:
  db-data-student-35:
